In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
from datetime import timedelta
import nltk

In [2]:
#critic_reviews = pd.read_csv('../input/rotten-tomatoes-movies-and-critic-reviews-dataset/rotten_tomatoes_critic_reviews.csv')
#critic_reviews

In [3]:
#critic_reviews.drop(['critic_name','top_critic', 'publisher_name', 'review_score', 'review_date'], axis = 1, inplace = True)
#critic_reviews

In [34]:
#critic_reviews.dropna(axis = 0, inplace=True)
#critic_reviews

In [5]:
#critic_reviews['rotten_tomatoes_link'].nunique()

In [6]:
#critic_reviews['review_type'].value_counts()

In [7]:
#critic_reviews['review_score'].value_counts()

#df_reviews = critic_reviews.loc[critic_reviews['rotten_tomatoes_link']=='m/0814255',['review_content']]
#list_rev= list(df_reviews['review_content'])
#df_reviews['review_content'].replace('.',' ')
#df_reviews['review_content'].replace(',',' ')
#list_rev= list(df_reviews['review_content'])
#list_rev
#e.split(' ',list_rev)

In [5]:
movies = pd.read_csv('../input/rotten-tomatoes-movies-and-critic-reviews-dataset/rotten_tomatoes_movies.csv')
movies

,rotten_tomatoes_link,movie_title,movie_info,critics_consensus,content_rating,genres,directors,authors,actors,original_release_date,...,production_company,tomatometer_status,tomatometer_rating,tomatometer_count,audience_status,audience_rating,audience_count,tomatometer_top_critics_count,tomatometer_fresh_critics_count,tomatometer_rotten_critics_count
0,m/0814255,Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...",Though it may seem like just another Harry Pot...,PG,"Action & Adventure, Comedy, Drama, Science Fic...",Chris Columbus,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,...,20th Century Fox,Rotten,49.0,149.0,Spilled,53.0,254421.0,43,73,76
1,m/0878835,Please Give,Kate (Catherine Keener) and her husband Alex (...,Nicole Holofcener's newest might seem slight i...,R,Comedy,Nicole Holofcener,Nicole Holofcener,"Catherine Keener, Amanda Peet, Oliver Platt, R...",2010-04-30,...,Sony Pictures Classics,Certified-Fresh,87.0,142.0,Upright,64.0,11574.0,44,123,19
2,m/10,10,"A successful, middle-aged Hollywood songwriter...",Blake Edwards' bawdy comedy may not score a pe...,R,"Comedy, Romance",Blake Edwards,Blake Edwards,"Dudley Moore, Bo Derek, Julie Andrews, Robert ...",1979-10-05,...,Waner Bros.,Fresh,67.0,24.0,Spilled,53.0,14684.0,2,16,8
3,m/1000013-12_angry_men,12 Angry Men (Twelve Angry Men),Following the closing arguments in a murder tr...,Sidney Lumet's feature debut is a superbly wri...,NR,"Classics, Drama",Sidney Lumet,Reginald Rose,"Martin Balsam, John Fiedler, Lee J. Cobb, E.G....",1957-04-13,...,Criterion Collection,Certified-Fresh,100.0,54.0,Upright,97.0,105386.0,6,54,0
4,m/1000079-20000_leagues_under_the_sea,"20,000 Leagues Under The Sea","In 1866, Professor Pierre M. Aronnax (Paul Luk...","One of Disney's finest live-action adventures,...",G,"Action & Adventure, Drama, Kids & Family",Richard Fleischer,Earl Felton,"James Mason, Kirk Douglas, Paul Lukas, Peter L...",1954-01-01,...,Disney,Fresh,89.0,27.0,Upright,74.0,68918.0,5,24,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17707,m/zoot_suit,Zoot Suit,Mexican-American gangster Henry Reyna (Daniel ...,NaN,R,"Drama, Musical & Performing Arts",Luis Valdez,Luis Valdez,"Daniel Valdez, Edward James Olmos, Charles Aid...",1981-10-02,...,MCA Universal Home Video,Rotten,56.0,9.0,Upright,74.0,1195.0,2,5,4
17708,m/zootopia,Zootopia,From the largest elephant to the smallest shre...,The brilliantly well-rounded Zootopia offers a...,PG,"Action & Adventure, Animation, Comedy","Byron Howard, Rich Moore, Jared Bush","Jared Bush, Phil Johnston","J.K. Simmons, Kristen Bell, Octavia Spencer, A...",2016-03-04,...,Walt Disney Animation Studios,Certified-Fresh,98.0,291.0,Upright,92.0,101511.0,50,285,7
17709,m/zorba_the_greek,Zorba the Greek,Traveling to inspect an abandoned mine his fat...,NaN,NR,"Action & Adventure, Art House & International,...",NaN,NaN,"Anthony Quinn, Alan Bates, Irene Papas, Lila K...",1964-12-17,...,Fox,Fresh,80.0,10.0,Upright,86.0,7146.0,0,8,2
17710,m/zulu,Zulu,"In 1879, the Zulu nation hands colonial Britis...",Zulu patiently establishes a cast of colorful ...,PG,"Classics, Drama","Cy Endfield, Cyril Endfield","Cy Endfield, John Prebble","Stanley Baker, Jack Hawkins, Ulla Jacobsson, J...",1964-06-17,...,Paramount Pictures,Fresh,96.0,23.0,Upright,91.0,30193.0,6,22,1
17711,m/zulu_dawn,Zulu Dawn,Sir Henry Bartle Frere's (John Mills) vastly o...,NaN,PG,"Action & Adventure, Art House & International,...",Douglas Hickox,"Cy Endfield, Anthony Storey","Burt Lancaster, Peter O'Toole, Simon Ward, Joh...",1979-12-14,...,Tango Entertainment,Rotten,50.0,8.0,Upright,62.0,4469.0,0,4,4

In [7]:
movies_1 = movies.iloc[:,:19]

In [11]:
#movies_1.info()

In [12]:
#movies_1.describe()

In [13]:
#movies_1['tomatometer_status'].unique()

In [14]:
#movies_1['audience_status'].unique()

In [15]:
#movies_1[['movie_title','tomatometer_status','audience_status']]

In [16]:
#Are there times when critics and viewers are in disagreement?
#def samerating(t):
#    tomato=t[0]
 #   audience=t[1]
  #  if tomato=='Rotten' and audience=='Spilled':
   #     return 'Critics and audience agree'
    #elif tomato=='Fresh'and audience=='Upright':
     #   return 'Critics and audience agree'
    #elif tomato=='Certified-Fresh'and audience=='Upright':
     #   return 'Critics and audience agree'
    #elif pd.isna(tomato) or pd.isna(audience):
     #   return 'N/A'
    #else:
     #   return 'Critics and audience disagree'

#tomato ='Rotten'
#audience= 'Upright'
#samerating(tomato,audience)
    
#movies_1['tomato_audience']= movies_1[['tomatometer_status','audience_status']].apply(samerating, axis=1)
#print(movies_1['tomato_audience'].value_counts(normalize=True)*100)
#movies_1

In [17]:
#disagree = movies_1[movies_1['tomato_audience']== 'Critics and audience disagree']
#disagree

In [18]:
#disagree.pivot_table(index='genres', values ='movie_title', aggfunc='count').sort_values(by='movie_title', ascending=False).head(10)

In [19]:
#agree = movies_1[movies_1['tomato_audience']== 'Critics and audience agree']
#agree.pivot_table(index='genres', values ='movie_title', aggfunc='count').sort_values(by='movie_title', ascending=False).head(10)

In [20]:
#movies_1.pivot_table(index='genres', values ='movie_title', aggfunc='count').sort_values(by='movie_title', ascending=False).head(10)

**1st Table - Get the movies for kids for the top studios**

In [9]:
## Conditions to filter the movies
cond2 = movies_1['tomatometer_status']!= 'Rotten' #Movies that have good rating
cond3 = movies_1['genres'].str.contains('Kids')
mov_kids = movies_1[cond2 & cond3]
mov_kids['production_company'].value_counts().head(20)

Walt Disney Pictures                41
Warner Bros. Pictures               35
Walt Disney Productions             25
20th Century Fox                    24
Buena Vista Pictures                22
Buena Vista                         21
Paramount Pictures                  18
Universal Pictures                  18
Columbia Pictures                   13
Sony Pictures Home Entertainment    12
Sony Pictures                       10
MGM                                 10
Warner Home Video                   10
WARNER BROTHERS PICTURES             9
Disney/Pixar                         8
Dreamworks                           7
Disney                               7
United Artists                       7
Netflix                              6
GKIDS                                6
Name: production_company, dtype: int64

In [24]:
## Create function to group together the same studios which are written in different ways

def producer(x):
    if 'warner' in str(x).lower() :
        return 'Warner Bros.'
    elif 'disney' in str(x).lower() :
        return 'Disney'
    elif 'mgm' in str(x).lower():
        return 'MGM'
    elif 'fox' in str(x).lower():
        return '20th Century Fox'
    elif 'paramount' in str(x).lower():
        return 'Paramount'
    elif 'buena vista' in str(x).lower():
        return 'Buena Vista'
    elif 'universal' in str(x).lower():
        return 'Universal'
    elif 'sony' in str(x).lower():
        return 'Sony'
    elif 'miramax' in str(x).lower():
        return 'Miramax'
    elif 'dreamworks' in str(x).lower():
        return 'Dreamworks'
    else:
        return str(x)
    
mov_kids['studio'] = mov_kids['production_company'].apply(producer)
mov_kids['studio'].value_counts()
moviesperstudio = pd.DataFrame(mov_kids['studio'].value_counts()).reset_index()
moviesperstudio.head(20)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

                    index  studio
0                  Disney      96
1            Warner Bros.      60
2             Buena Vista      50
3        20th Century Fox      39
4               Paramount      34
5                    Sony      29
6               Universal      27
7                     MGM      15
8       Columbia Pictures      13
9              Dreamworks      12
10                    nan      12
11         United Artists       7
12                  GKIDS       6
13                Netflix       6
14         Focus Features       5
15  Artisan Entertainment       4
16                Miramax       3
17        New Line Cinema       3
18     Giant Screen Films       2
19          Tokuma Shoten       2

In [26]:
dfstudios = mov_kids.merge(moviesperstudio, how='inner', left_on='studio', right_on='index')
dfstudios

,rotten_tomatoes_link,movie_title,movie_info,critics_consensus,content_rating,genres,directors,authors,actors,original_release_date,...,production_company,tomatometer_status,tomatometer_rating,tomatometer_count,audience_status,audience_rating,audience_count,studio_x,index,studio_y
0,m/1000079-20000_leagues_under_the_sea,"20,000 Leagues Under The Sea","In 1866, Professor Pierre M. Aronnax (Paul Luk...","One of Disney's finest live-action adventures,...",G,"Action & Adventure, Drama, Kids & Family",Richard Fleischer,Earl Felton,"James Mason, Kirk Douglas, Paul Lukas, Peter L...",1954-01-01,...,Disney,Fresh,89.0,27.0,Upright,74.0,68918.0,Disney,Disney,96
1,m/1007839-freaky_friday,Freaky Friday,"Annabel Andrews (Jodie Foster) and her mother,...",Freaky Friday is too well-behaved to live up t...,G,"Comedy, Kids & Family, Science Fiction & Fantasy",Gary Nelson,Mary Rodgers,"Barbara Harris, Jodie Foster, John Astin, Pats...",1976-12-17,...,Disney,Fresh,70.0,23.0,Spilled,57.0,65759.0,Disney,Disney,96
2,m/1012813-love_bug,The Love Bug,Race car driver Jim Douglas (Dean Jones) and h...,NaN,G,"Action & Adventure, Classics, Comedy, Kids & F...",Robert Stevenson,"Bill Walsh, Don DaGradi","Dean Jones, Michele Lee, Buddy Hackett, David ...",1969-03-13,...,Disney,Fresh,76.0,17.0,Upright,66.0,39845.0,Disney,Disney,96
3,m/1016213-peter_pan,Peter Pan,"In this Disney animated film, Wendy (Kathryn B...",Though it doesn't delve deeply into the darkne...,G,"Animation, Kids & Family, Musical & Performing...","Wilfred Jackson, Clyde Geronimi, Hamilton Luske","Ralph Wright, Erdman Penner, Joe Rinaldi, Will...","Bobby Driscoll, Kathryn Beaumont, Hans Conried...",1953-02-05,...,Walt Disney,Fresh,81.0,36.0,Upright,80.0,277986.0,Disney,Disney,96
4,m/1016512-pollyanna,Pollyanna,Young orphan Pollyanna (Hayley Mills) believes...,NaN,G,"Drama, Kids & Family",David Swift,NaN,"Hayley Mills, Jane Wyman, Richard Egan, Karl M...",1960-05-19,...,Walt Disney Productions,Fresh,86.0,14.0,Upright,79.0,20895.0,Disney,Disney,96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545,m/toys_in_the_attic_2012,Toys In The Attic (Na Pude),"A teddy bear, a mechanical mouse and a marione...",NaN,PG,"Animation, Kids & Family, Science Fiction & Fa...","Jirí Barta, Vivian Schilling","Edgar Dutka, Jirí Barta","Forest Whitaker, Joan Cusak, Cary Elwes, Vivia...",2012-09-07,...,Hannover House,Fresh,73.0,15.0,Upright,80.0,894.0,Hannover House,Hannover House,1
546,m/velveteen_rabbit,The Velveteen Rabbit,"After the death of his mother, Toby Morgan (Ma...",NaN,G,Kids & Family,"Michael Landon Jr., Michael Landon","Michael Landon Jr., Cindy Kelley","Matthew Harbour, Kevin Jubinville, Una Kay, To...",2009-02-27,...,Family1 Films,Fresh,86.0,7.0,Upright,66.0,7667.0,Family1 Films,Family1 Films,1
547,m/ways_to_live_forever,Ways To Live Forever,"Sam needs to learn about UFOs, horror movies a...",NaN,PG-13,"Drama, Kids & Family",Gustavo Ron,Gustavo Ron,"Ben Chaplin, Emilia Fox, Greta Scacchi, Robbie...",2013-07-19,...,World Wide motion Picturess Co.,Fresh,83.0,6.0,Upright,78.0,519.0,World Wide motion Picturess Co.,World Wide motion Picturess Co.,1
548,m/white_fang_2_myth_of_the_white_wolf,White Fang 2: Myth of the White Wolf,"In this sequel, the hero of the first film, Ja...",NaN,PG,"Action & Adventure, Kids & Family",Ken Olin,David Fallon,"Scott Bairstow, Charmaine Craig, Al Harrington...",1994-04-15,...,MVD Music Video,Fresh,71.0,7.0,Spilled,47.0,8829.0,MVD Music Video,MVD Music Video,1
549,m/young_lions,The Young Lions,Three soldiers endure the crucible of World Wa...,NaN,G,"Action & Adventure, Classics, Drama, Kids & Fa...",Edward Dmytryk,Edward Anhalt,"Marlon Brando, Montgomery Clift, Dean Martin, ...",1958-04-02,...,WGBH Boston Video,Fresh,71.0,7.0,Upright,77.0,2885.0,WGBH Boston Video,WGBH Boston Video,1

In [27]:
dfstudios['tomatometer_count'].describe()

count    547.000000
mean      76.758684
std       85.546125
min        5.000000
25%       13.000000
50%       35.000000
75%      128.000000
max      443.000000
Name: tomatometer_count, dtype: float64

In [28]:
dfstudios['studio_y'].describe()

count    550.000000
mean      37.414545
std       33.299477
min        1.000000
25%        4.000000
50%       34.000000
75%       60.000000
max       96.000000
Name: studio_y, dtype: float64

In [32]:
cond_a = dfstudios['studio_y']>6 #get studios which produced more than 6 movies
cond_b = dfstudios['tomatometer_count']>35 #median values
top_studios = pd.DataFrame(dfstudios[cond_a & cond_b][['rotten_tomatoes_link','movie_title','tomatometer_rating','studio_x','original_release_date']])

top_studios['original_release_date'].fillna(2001, inplace = True) #there was 1 movies without year so we checked online to get the year and filled it our table

#convert 'original_release_date' into a new column as an integer
top_studios['year_release'] = top_studios['original_release_date'].astype(str)
top_studios['year_release'] = top_studios['year_release'].apply(lambda x : x[0:4])
top_studios['year_release'] = top_studios['year_release'].apply(lambda x : int(x))

top_studios = top_studios.sort_values(by='tomatometer_rating', ascending=False)
top_studios.rename(columns={'movie_title': 'Movie Title','tomatometer_rating': 'Rotten Tomatoes rating', 'studio_x':'Studio', 'year_release':'Year'}, inplace=True) 
top_studios
#print(type(top_studios['year_release']))

,rotten_tomatoes_link,Movie Title,Rotten Tomatoes rating,Studio,original_release_date,Year
347,m/toy_story,Toy Story,100.0,Buena Vista,1995-11-22,1995
50,m/mary_poppins,Mary Poppins,100.0,Disney,1964-08-26,1964
235,m/paddington_2,Paddington 2,100.0,Warner Bros.,2018-01-12,2018
348,m/toy_story_2,Toy Story 2,100.0,Buena Vista,1999-11-24,1999
32,m/finding_nemo,Finding Nemo,99.0,Disney,2003-05-30,2003
...,...,...,...,...,...,...
97,m/10005499-oliver_twist,Oliver Twist,61.0,Sony,2005-09-30,2005
13,m/alexander_and_the_terrible_horrible_no_good_...,"Alexander and the Terrible, Horrible, No Good,...",61.0,Disney,2014-10-10,2014
379,m/the_grinch,The Grinch,60.0,Universal,2018-11-09,2018
350,m/tuck_everlasting,Tuck Everlasting,60.0,Buena Vista,2002-10-22,2002
339,m/recess_schools_out,Recess: School's Out,60.0,Buena Vista,2001-02-16,2001

In [29]:
top_studios.to_csv('kids_movies.csv',index = False)

**2nd Table - Full RT tomatoes database to do the join with IMDB**

In [30]:
movies_1['dir_mov']=movies_1['directors']+movies_1['movie_title']
movies_1

,rotten_tomatoes_link,movie_title,movie_info,critics_consensus,content_rating,genres,directors,authors,actors,original_release_date,streaming_release_date,runtime,production_company,tomatometer_status,tomatometer_rating,tomatometer_count,audience_status,audience_rating,audience_count,dir_mov
0,m/0814255,Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...",Though it may seem like just another Harry Pot...,PG,"Action & Adventure, Comedy, Drama, Science Fic...",Chris Columbus,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,2015-11-25,119.0,20th Century Fox,Rotten,49.0,149.0,Spilled,53.0,254421.0,Chris ColumbusPercy Jackson & the Olympians: T...
1,m/0878835,Please Give,Kate (Catherine Keener) and her husband Alex (...,Nicole Holofcener's newest might seem slight i...,R,Comedy,Nicole Holofcener,Nicole Holofcener,"Catherine Keener, Amanda Peet, Oliver Platt, R...",2010-04-30,2012-09-04,90.0,Sony Pictures Classics,Certified-Fresh,87.0,142.0,Upright,64.0,11574.0,Nicole HolofcenerPlease Give
2,m/10,10,"A successful, middle-aged Hollywood songwriter...",Blake Edwards' bawdy comedy may not score a pe...,R,"Comedy, Romance",Blake Edwards,Blake Edwards,"Dudley Moore, Bo Derek, Julie Andrews, Robert ...",1979-10-05,2014-07-24,122.0,Waner Bros.,Fresh,67.0,24.0,Spilled,53.0,14684.0,Blake Edwards10
3,m/1000013-12_angry_men,12 Angry Men (Twelve Angry Men),Following the closing arguments in a murder tr...,Sidney Lumet's feature debut is a superbly wri...,NR,"Classics, Drama",Sidney Lumet,Reginald Rose,"Martin Balsam, John Fiedler, Lee J. Cobb, E.G....",1957-04-13,2017-01-13,95.0,Criterion Collection,Certified-Fresh,100.0,54.0,Upright,97.0,105386.0,Sidney Lumet12 Angry Men (Twelve Angry Men)
4,m/1000079-20000_leagues_under_the_sea,"20,000 Leagues Under The Sea","In 1866, Professor Pierre M. Aronnax (Paul Luk...","One of Disney's finest live-action adventures,...",G,"Action & Adventure, Drama, Kids & Family",Richard Fleischer,Earl Felton,"James Mason, Kirk Douglas, Paul Lukas, Peter L...",1954-01-01,2016-06-10,127.0,Disney,Fresh,89.0,27.0,Upright,74.0,68918.0,"Richard Fleischer20,000 Leagues Under The Sea"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17707,m/zoot_suit,Zoot Suit,Mexican-American gangster Henry Reyna (Daniel ...,NaN,R,"Drama, Musical & Performing Arts",Luis Valdez,Luis Valdez,"Daniel Valdez, Edward James Olmos, Charles Aid...",1981-10-02,2016-04-19,104.0,MCA Universal Home Video,Rotten,56.0,9.0,Upright,74.0,1195.0,Luis ValdezZoot Suit
17708,m/zootopia,Zootopia,From the largest elephant to the smallest shre...,The brilliantly well-rounded Zootopia offers a...,PG,"Action & Adventure, Animation, Comedy","Byron Howard, Rich Moore, Jared Bush","Jared Bush, Phil Johnston","J.K. Simmons, Kristen Bell, Octavia Spencer, A...",2016-03-04,2016-06-07,108.0,Walt Disney Animation Studios,Certified-Fresh,98.0,291.0,Upright,92.0,101511.0,"Byron Howard, Rich Moore, Jared BushZootopia"
17709,m/zorba_the_greek,Zorba the Greek,Traveling to inspect an abandoned mine his fat...,NaN,NR,"Action & Adventure, Art House & International,...",NaN,NaN,"Anthony Quinn, Alan Bates, Irene Papas, Lila K...",1964-12-17,2015-11-25,142.0,Fox,Fresh,80.0,10.0,Upright,86.0,7146.0,NaN
17710,m/zulu,Zulu,"In 1879, the Zulu nation hands colonial Britis...",Zulu patiently establishes a cast of colorful ...,PG,"Classics, Drama","Cy Endfield, Cyril Endfield","Cy Endfield, John Prebble","Stanley Baker, Jack Hawkins, Ulla Jacobsson, J...",1964-06-17,2017-01-08,135.0,Paramount Pictures,Fresh,96.0,23.0,Upright,91.0,30193.0,"Cy Endfield, Cyril EndfieldZulu"
17711,m/zulu_dawn,Zulu Dawn,Sir Henry Bartle Frere's (John Mills) vastly o...,NaN,PG,"Action & Adventure, Art House & International,...",Douglas Hickox,"Cy Endfield, Anthony Storey","Burt Lancaster, Peter O'Toole, Simon Ward, Joh...",1979-12-14,2016-03-22,121.0,Tango Entertainment,Rotten,50.0,8.0,Upright,62.0,4469.0,Douglas HickoxZulu Dawn

In [31]:
movies_1.to_csv('out4.csv',index = False)